### ISSUE TITLE
Make diamond threshold customizable on badges

### ISSUE THREAD

**Issue by MichaelSlatteryDev** [CollActionteam/collaction_api#120]
Make the diamond threshold value customizable and keep hardcoded values for the other tiers. We can pass this in through the crowdaction in the delegate-badges command. This means we will need to add a diamond threshold to the crowdaction persistence too since the badges are delegated by the CRON and not a call.
We could do this by adding a new `BadgeConfig` object inside the crowdactions. For now this would only store the diamond threshold value but we may add new things to it in the future.

**Comment by imReset** [comment]
#129

**Comment by imReset** [comment]
#129
