### ISSUE TITLE
[Board] Add endpoints to fetch all forums and fetch a forum and it's children by the forumId

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_api#91]
TBD

**Comment by MichaelSlatteryDev** [comment]
We need two calls for this.
One that fetches all forums
One that fetches a forum and all it's children

For the second call we'll need to query all forums `parentList` and return any that contain the initial requested forum. This way we know which forums contain which children.
```
let forums = await this.forumRep.findAll({ parentList: { in: [forumId] });
```

**Comment by MichaelSlatteryDev** [comment]
This is all covered in #133
Closing this as a duplicate
